ALTER TABLE "User" ADD COLUMN "loginStreak"    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "lastLoginDate"  TEXT    NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "claimedMissions" TEXT   NOT NULL DEFAULT '[]';
